// const data = {
//   products: [
//     {
//       _id: "1",
//       name: "nike slim shirt",
//       slug: "nike-slim-shirt",
//       category: "Shirts",
//       image: "/images/p1.jpg",
//       price: 120,
//       countInStock: 10,
//       brand: "nike",
//       rating: 4.5,
//       numReviews: 10,
//       description: "high quality product",
//     },
//     {
//       _id: "2",
//       name: "nike slim pant",
//       slug: "nike-slim-pant",
//       category: "Pants",
//       image: "/images/p2.jpg",
//       price: 120,
//       countInStock: 10,
//       brand: "nike",
//       rating: 4.5,
//       numReviews: 10,
//       description: "high quality product",
//     },
//     {
//       _id: "3",
//       name: "Adidas slim shirt",
//       slug: "adidas-slim-shirt",
//       category: "Shirts",
//       image: "/images/p3.jpg",
//       price: 120,
//       countInStock: 0,
//       brand: "adidas",
//       rating: 4.5,
//       numReviews: 10,
//       description: "high quality product",
//     },
//     {
//       _id: "4",
//       name: "nike pant",
//       slug: "nike-pant",
//       category: "Shirts",
//       image: "/images/p4.jpg",
//       price: 120,
//       countInStock: 10,
//       brand: "adidas",
//       rating: 4.5,
//       numReviews: 10,
//       description: "high quality product",
//     },
//   ],
// };
// export default data;
